// src/vuejs/App.vue
<template>
  <div class="app">
    <div>{{count}} Comments</div>
    <CommentList :comments="comments" :hasMore="hasMore" @onLoadMore="onLoadMore" />
    <CommentForm @onAdd="onAdd" />
  </div>
</template>

<script>
import CommentList from './components/CommentList'
import CommentForm from './components/CommentForm'

let data = {
  comments: [
    { id: 5, message: "Comment 5", created: new Date(new Date().getTime() - 60000) },
    { id: 6, message: "Comment 6", created: new Date(new Date().getTime() - 50000) }
  ],
  count: 6,
  hasMore: true
}

export default {
  name: 'app',
  data() {
    return data
  },
  methods: {
    onAdd: function (message) {
      let newId = data.comments[data.comments.length - 1].id + 1
      Object.assign(data, {
        comments: data.comments.concat({ id: newId, message: message, created: new Date() }),
        count: data.count + 1
      })
    },
    onLoadMore: function () {
      Object.assign(data, {
        comments: [
          { id: 1, message: 'Comment 1', created: new Date(new Date().getTime() - 1000000) },
          { id: 2, message: 'Comment 2', created: new Date(new Date().getTime() - 900000) },
          { id: 3, message: 'Comment 3', created: new Date(new Date().getTime() - 800000) },
          { id: 4, message: 'Comment 4', created: new Date(new Date().getTime() - 700000) }
        ].concat(data.comments),
        hasMore: false
      })
    }
  },
  components: { CommentList, CommentForm }
}
</script>

<style>

</style>

// src/react/containers/App.js
import React, { Component, PropTypes } from 'react'

import CommentList from '../components/CommentList'
import CommentForm from '../components/CommentForm'

class App extends Component {

  constructor(props, context) {
    super(props, context)
    this.state = {
      comments: [
        {id: 5, message:'Comment 5', created: new Date(new Date().getTime() - 600000)},
        {id: 6, message:'Comment 6', created: new Date(new Date().getTime() - 500000)},
      ],
      count: 6,
      hasMoreComments: true
    }
  }

  handleLoadMore() {
    const { comments } = this.state
    this.setState({
      comments: [
        {id: 1, message: 'Comment 1', created: new Date(new Date().getTime() - 1000000)},
        {id: 2, message: 'Comment 2', created: new Date(new Date().getTime() - 900000)},
        {id: 3, message: 'Comment 3', created: new Date(new Date().getTime() - 800000)},
        {id: 4, message: 'Comment 4', created: new Date(new Date().getTime() - 700000)}
      ].concat(comments),
      hasMoreComments: false
    })
  }

  handleAdd(message) {
    const { comments, count } = this.state
    let newId = comments[comments.length - 1].id + 1
    this.setState({
      comments: comments.concat({id: newId, message: message, created: new Date()}),
      count: count + 1
    })
  }

  render() {
    const { comments, count, hasMoreComments } = this.state
    return (
      <div className="app">
        <div>{count} Comments</div>
        <CommentList comments={comments} hasMore={hasMoreComments} onLoadMore={this.handleLoadMore.bind(this)} />
        <CommentForm onAdd={this.handleAdd.bind(this)} />
      </div>
    )
  }
}

export default App
