// src/vuejs/components/CommentList.vue
<template>
  <div>
    <button v-if="hasMore" class="btn-more" v-on:click="onLoadMore">more comment</button>
    <Comment v-for="comment in comments" :key="comment.id" :comment="comment" />
  </div>
</template>

<script>
import Comment from './Comment'

export default {
  name: 'list',
  props: [
    'comments',
    'hasMore'
  ],
  model: {
    event: "onLoadMore"
  },
  methods: {
    onLoadMore: function (e) {
      this.$emit('onLoadMore')
    }
  },
  components: { Comment }
}
</script>

// src/react/components/CommentList.js
import React, { Component, PropTypes } from 'react'

import Comment from './Comment'

class CommentList extends Component {
  render() {
    const { comments, hasMore, onLoadMore } = this.props
    return (
      <div>
        {hasMore &&
          <button className="btn-more" onClick={onLoadMore}>more comment</button>
        }
        {comments.map(item =>
          <Comment key={item.id} comment={item} />
        )}
      </div>
    )
  }
}

CommentList.propTypes = {
  comments: PropTypes.array.isRequired,
  hasMore: PropTypes.bool.isRequired,
  onLoadMore: PropTypes.func.isRequired
}

export default CommentList
